#pragma once

#define IDI_APPICON 101

#define VER_FILEVERSION 0, 2, 0
#define VER_FILEVERSION_STR "0.2.0\0"

#define VER_PRODUCTVERSION 0, 2, 0
#define VER_PRODUCTVERSION_STR "0.2.0\0"

#define VER_COMPANYNAME_STR "MONAD Demogroup"
#define VER_FILEDESCRIPTION_STR "Axiom: node-based VSTi"
#define VER_INTERNALNAME_STR "Axiom"
#define VER_LEGALCOPYRIGHT_STR "Copyright 2018 MONAD"
#define VER_LEGALTRADEMARKS1_STR "Source is licensed under MIT"
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "axiom.exe"
#define VER_PRODUCTNAME_STR "Axiom"
